### ISSUE TITLE
Fatal error: Call to undefined method Doctrine\ORM\Configuration::setSecondLevelCacheEnabled

### ISSUE THREAD

**Issue by dfreudenberger** [guilhermeblanco/zendframework1-doctrine2#74]
Unfortunately changes made in https://github.com/guilhermeblanco/zendframework1-doctrine2/pull/73 are not compatible with doctrine/dbal < 2.5

I see two fixes:

1. raise minimum version to ~2.5
2. check for support of second level cache

I'll happily provide a fix / pr for the preferred fix. 

@guilhermeblanco what do you think?

**Comment by emiliodeg** [comment]
I added a little solution for this issue https://github.com/guilhermeblanco/zendframework1-doctrine2/pull/75
